"""add quantities to grocery_list_items

Revision ID: 0cff1d550060
Revises: a2ad2cc01282
Create Date: 2026-06-20 14:00:14.031751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cff1d550060'
down_revision: Union[str, Sequence[str], None] = 'a2ad2cc01282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grocery_list_items', sa.Column('quantities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grocery_list_items', 'quantities')
    # ### end Alembic commands ###
