"""add needs_review to recipe_ingredients

Revision ID: f8b33cad0d3f
Revises: 2e22c88cc0ef
Create Date: 2026-06-19 14:25:33.366257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b33cad0d3f'
down_revision: Union[str, Sequence[str], None] = '2e22c88cc0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('needs_review', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'needs_review')
    # ### end Alembic commands ###
